config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/marekandreas/elpa:
      branch: master
      repo: https://github.com/marekandreas/elpa
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/marekandreas/elpa git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-tangerine-gerbil.sh
        container: qc.acc_shaggy-copper-crab
  QC.Doc:
    repos:
      github.com/marekandreas/elpa find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-goldenrod-liger.sh
        container: qc.doc_surly-bistre-eel
      github.com/marekandreas/elpa git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-asparagus-nightingale.sh
        container: qc.doc_messy-xanthic-coati
      github.com/marekandreas/elpa markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-salmon-baboon.sh
        container: qc.doc_snippy-vermilion-wrasse
  QC.Lic:
    repos:
      github.com/marekandreas/elpa licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-persimmon-owl.sh
        container: qc.lic_messy-violet-crane
  QC.Sec:
    repos:
      github.com/marekandreas/elpa bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-tangerine-donkey.sh
        container: qc.sec_scummy-emerald-squid
  QC.Sty:
    repos:
      github.com/marekandreas/elpa flake8:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-buff-hare.sh
        container: qc.sty_homely-magnolia-wildebeest
  QC.Ver:
    repos:
      github.com/marekandreas/elpa get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-myrtle-camel.sh
        container: qc.ver_homely-chartreuse-panda
timeout: 1800
