config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/marekandreas/elpa:
      branch: master
      repo: https://github.com/marekandreas/elpa
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/marekandreas/elpa git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-charcoal-discus.sh
        container: qc.acc_freaky-pear-buzzard
  QC.Doc:
    repos:
      github.com/marekandreas/elpa find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-green-dingo.sh
        container: qc.doc_pokey-rose-chamois
      github.com/marekandreas/elpa git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-scarlet-lemur.sh
        container: qc.doc_skimpy-vermilion-sparrow
      github.com/marekandreas/elpa markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-champagne-chimpanzee.sh
        container: qc.doc_cranky-plum-coati
  QC.Lic:
    repos:
      github.com/marekandreas/elpa licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-mustard-audemer.sh
        container: qc.lic_hazy-crimson-reindeer
  QC.Sec:
    repos:
      github.com/marekandreas/elpa bandit:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-wisteria-swan.sh
        container: qc.sec_cranky-smalt-frigatebird
  QC.Sty:
    repos:
      github.com/marekandreas/elpa flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-teal-chamois.sh
        container: qc.sty_skimpy-cerise-newfoundland
  QC.Ver:
    repos:
      github.com/marekandreas/elpa get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-heliotrope-caiman.sh
        container: qc.ver_silly-carmine-harrier
timeout: 1800
